/**
 * Local Token Vault
 *
 * Persistently stores the original cleartext values for tokens generated by the Redactor.
 * Allows the local Proxy to re-hydrate results before returning them to the agent.
 */

/**
 * Vault for storing and re-applying redacted tokens.
 */
export class TokenVault {
  private vault: Map<string, { value: string; timestamp: number }> = new Map();
  private readonly ttl: number;

  /**
   * @param ttlMs - Time to live in milliseconds (default: 1 hour)
   */
  constructor(ttlMs: number = 60 * 60 * 1000) {
    this.ttl = ttlMs;
  }

  /**
   * Save a set of tokens and their original values to the vault.
   * 
   * @param tokens - Map of tokens to cleartext values.
   */
  public saveTokens(tokens: Map<string, string>): void {
    const now = Date.now();
    for (const [token, value] of tokens) {
      this.vault.set(token, { value, timestamp: now });
    }
    this.prune();
  }

  /**
   * Re-hydrate a string or object containing tokens back into cleartext.
   * 
   * @param input - The string or object containing tokens.
   * @returns The original cleartext content.
   */
  public rehydrate(input: any): any {
    // Return early if no tokens in vault
    if (this.vault.size === 0) return input;

    // Security: Use structuredClone for safe deep copies (addresses review)
    let output: any;
    try {
      output = typeof input === 'object' && input !== null 
        ? structuredClone(input) 
        : input;
    } catch (e) {
      output = input;
    }

    const process = (node: any): any => {
      if (typeof node === 'string') {
        let text = node;
        // Efficiently replace all tokens
        for (const [token, entry] of this.vault.entries()) {
          text = text.split(token).join(entry.value);
        }
        return text;
      }

      if (Array.isArray(node)) {
        return node.map(item => process(item));
      }

      if (node !== null && typeof node === 'object') {
        const obj: any = {};
        for (const [key, value] of Object.entries(node)) {
          obj[key] = process(value);
        }
        return obj;
      }

      return node;
    };

    return process(output);
  }

  /**
   * Create a stateful rehydrator for processing streaming chunks.
   * Handles cases where tokens are split across chunks.
   */
  public createStreamingRehydrator() {
    let buffer = '';
    const maxTokenLen = Math.max(...[...this.vault.keys()].map(t => t.length), 0);

    // Accumulate content fields across SSE events to reassemble split tokens.
    // Cap buffer size to prevent unbounded memory growth on very long streams.
    const MAX_BUFFER_SIZE = 1024 * 1024; // 1 MB per field
    const contentBuffers: Record<string, string> = {};
    const CONTENT_FIELDS = ['content', 'reasoning_content', 'partial_json'];

    const rehydrateText = (text: string): string => {
      for (const [token, entry] of this.vault.entries()) {
        text = text.split(token).join(entry.value);
      }
      return text;
    };

    const flushField = (field: string): string => {
      if (!contentBuffers[field]) return '';
      const result = rehydrateText(contentBuffers[field]);
      contentBuffers[field] = '';
      return result;
    };

    return (chunk: string): string => {
      buffer += chunk;

      // Detect if this is an SSE stream (contains "data: " lines)
      const isSSE = buffer.includes('data: ');

      if (!isSSE) {
        // Raw text mode: hold back potential partial tokens
        let holdBack = 0;
        if (maxTokenLen > 0) {
          for (const [token] of this.vault.entries()) {
            for (let prefixLen = 1; prefixLen < token.length; prefixLen++) {
              if (buffer.endsWith(token.substring(0, prefixLen))) {
                holdBack = Math.max(holdBack, prefixLen);
              }
            }
          }
        }
        const releaseEnd = buffer.length - holdBack;
        let text = buffer.substring(0, releaseEnd);
        buffer = buffer.substring(releaseEnd);
        return rehydrateText(text);
      }

      // SSE mode: parse each data line, accumulate content fields, rehydrate
      // Only hold back the last segment if it doesn't end with \n (incomplete line)
      let processable: string;
      if (buffer.endsWith('\n')) {
        processable = buffer;
        buffer = '';
      } else {
        const lastNewline = buffer.lastIndexOf('\n');
        if (lastNewline === -1) {
          return ''; // no complete lines yet
        }
        processable = buffer.substring(0, lastNewline + 1);
        buffer = buffer.substring(lastNewline + 1);
      }
      const lines = processable.split('\n');
      // Remove trailing empty string from split (the part after last \n)
      if (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();

      const outputLines: string[] = [];

      for (const line of lines) {
        if (!line.startsWith('data: ') || line.trim() === 'data: [DONE]') {
          outputLines.push(line);
          continue;
        }

        let parsed: any;
        try {
          parsed = JSON.parse(line.slice(6));
        } catch {
          outputLines.push(rehydrateText(line));
          continue;
        }

        // Look for delta content in OpenAI/ZhipuAI format
        const delta = parsed?.choices?.[0]?.delta;
        // Look for delta content in Anthropic format
        const anthDelta = parsed?.delta;

        const target = delta || anthDelta;
        if (!target) {
          outputLines.push('data: ' + JSON.stringify(this.rehydrate(parsed)));
          continue;
        }

        let modified = false;
        for (const field of CONTENT_FIELDS) {
          const textField = field === 'content' ? 'text' : null;
          const actualField = typeof target[field] === 'string' ? field
            : (textField && typeof target[textField] === 'string') ? textField
            : null;
          if (!actualField) continue;

          const bufKey = actualField;
          contentBuffers[bufKey] = (contentBuffers[bufKey] || '') + target[actualField];

          // Cap buffer size: flush everything if it grows too large
          if (contentBuffers[bufKey]!.length > MAX_BUFFER_SIZE) {
            target[actualField] = flushField(bufKey);
            modified = true;
            continue;
          }

          const buf = contentBuffers[bufKey]!;
          const lastBracket = buf.lastIndexOf('[');
          // Only treat as partial token if the text after '[' looks like a
          // token prefix (uppercase letter or underscore), not JSON array content.
          const hasPartialToken = maxTokenLen > 0 && lastBracket >= 0 &&
            !buf.substring(lastBracket).includes(']') &&
            buf.length - lastBracket < maxTokenLen &&
            /^\[[A-Z_]/.test(buf.substring(lastBracket));

          if (hasPartialToken) {
            const safe = buf.substring(0, lastBracket);
            contentBuffers[bufKey] = buf.substring(lastBracket);
            target[actualField] = rehydrateText(safe);
          } else {
            target[actualField] = flushField(bufKey);
          }
          modified = true;
        }

        // Re-serialize with original SSE framing
        outputLines.push('data: ' + JSON.stringify(parsed));
      }

      return outputLines.join('\n') + '\n';
    };
  }

  /**
   * Remove expired tokens from the vault.
   */
  private prune(): void {
    const now = Date.now();
    for (const [token, entry] of this.vault.entries()) {
      if (now - entry.timestamp > this.ttl) {
        this.vault.delete(token);
      }
    }
  }

  /**
   * Get the original value for a specific token.
   * 
   * @param token - The token to look up.
   * @returns The original cleartext or undefined if not found.
   */
  public get(token: string): string | undefined {
    const entry = this.vault.get(token);
    return entry?.value;
  }

  /**
   * Clear the vault for a new session.
   */
  public clear(): void {
    this.vault.clear();
  }

  /**
   * Get the number of tokens currently in the vault.
   */
  public get size(): number {
    return this.vault.size;
  }
}
