/**
 * Local Token Vault
 *
 * Persistently stores the original cleartext values for tokens generated by the Redactor.
 * Allows the local Proxy to re-hydrate results before returning them to the agent.
 */

/**
 * Vault for storing and re-applying redacted tokens.
 */
export class TokenVault {
  private vault: Map<string, string> = new Map();

  /**
   * Save a set of tokens and their original values to the vault.
   * 
   * @param tokens - Map of tokens to cleartext values.
   */
  public saveTokens(tokens: Map<string, string>): void {
    for (const [token, value] of tokens) {
      this.vault.set(token, value);
    }
  }

  /**
   * Re-hydrate a string or object containing tokens back into cleartext.
   * 
   * @param input - The string or object containing tokens.
   * @returns The original cleartext content.
   */
  public rehydrate(input: any): any {
    // Return early if no tokens in vault
    if (this.vault.size === 0) return input;

    // Deep copy input for objects
    const output = typeof input === 'object' && input !== null 
      ? JSON.parse(JSON.stringify(input)) 
      : input;

    const process = (node: any): any => {
      if (typeof node === 'string') {
        let text = node;
        // Efficiently replace all tokens
        for (const [token, value] of this.vault.entries()) {
          text = text.split(token).join(value);
        }
        return text;
      }

      if (Array.isArray(node)) {
        return node.map(item => process(item));
      }

      if (node !== null && typeof node === 'object') {
        const obj: any = {};
        for (const [key, value] of Object.entries(node)) {
          obj[key] = process(value);
        }
        return obj;
      }

      return node;
    };

    return process(output);
  }

  /**
   * Get the original value for a specific token.
   * 
   * @param token - The token to look up.
   * @returns The original cleartext or undefined if not found.
   */
  public get(token: string): string | undefined {
    return this.vault.get(token);
  }

  /**
   * Clear the vault for a new session.
   */
  public clear(): void {
    this.vault.clear();
  }

  /**
   * Get the number of tokens currently in the vault.
   */
  public get size(): number {
    return this.vault.size;
  }
}
