/**
 * Local Token Vault
 *
 * Persistently stores the original cleartext values for tokens generated by the Redactor.
 * Allows the local Proxy to re-hydrate results before returning them to the agent.
 */

/**
 * Vault for storing and re-applying redacted tokens.
 */
export class TokenVault {
  private vault: Map<string, { value: string; timestamp: number }> = new Map();
  private readonly ttl: number;

  /**
   * @param ttlMs - Time to live in milliseconds (default: 1 hour)
   */
  constructor(ttlMs: number = 60 * 60 * 1000) {
    this.ttl = ttlMs;
  }

  /**
   * Save a set of tokens and their original values to the vault.
   * 
   * @param tokens - Map of tokens to cleartext values.
   */
  public saveTokens(tokens: Map<string, string>): void {
    const now = Date.now();
    for (const [token, value] of tokens) {
      this.vault.set(token, { value, timestamp: now });
    }
    this.prune();
  }

  /**
   * Re-hydrate a string or object containing tokens back into cleartext.
   * 
   * @param input - The string or object containing tokens.
   * @returns The original cleartext content.
   */
  public rehydrate(input: any): any {
    // Return early if no tokens in vault
    if (this.vault.size === 0) return input;

    // Deep copy input for objects
    const output = typeof input === 'object' && input !== null 
      ? JSON.parse(JSON.stringify(input)) 
      : input;

    const process = (node: any): any => {
      if (typeof node === 'string') {
        let text = node;
        // Efficiently replace all tokens
        for (const [token, entry] of this.vault.entries()) {
          text = text.split(token).join(entry.value);
        }
        return text;
      }

      if (Array.isArray(node)) {
        return node.map(item => process(item));
      }

      if (node !== null && typeof node === 'object') {
        const obj: any = {};
        for (const [key, value] of Object.entries(node)) {
          obj[key] = process(value);
        }
        return obj;
      }

      return node;
    };

    return process(output);
  }

  /**
   * Remove expired tokens from the vault.
   */
  private prune(): void {
    const now = Date.now();
    for (const [token, entry] of this.vault.entries()) {
      if (now - entry.timestamp > this.ttl) {
        this.vault.delete(token);
      }
    }
  }

  /**
   * Get the original value for a specific token.
   * 
   * @param token - The token to look up.
   * @returns The original cleartext or undefined if not found.
   */
  public get(token: string): string | undefined {
    const entry = this.vault.get(token);
    return entry?.value;
  }

  /**
   * Clear the vault for a new session.
   */
  public clear(): void {
    this.vault.clear();
  }

  /**
   * Get the number of tokens currently in the vault.
   */
  public get size(): number {
    return this.vault.size;
  }
}
